### ISSUE TITLE
Installation/update of flat-remix-icon-theme on Fedora fails

### ISSUE THREAD

**Issue by cmcornejocrespo** [daniruiz/flat-remix#188] opened 2022-01-09 18:57 UTC
It looks like flat-remix-icon-theme-0.0.20211214-2.fc35.noarch is broken. It worked perfectly before this update

![image](https://user-images.githubusercontent.com/1030528/148696428-6c4c62ae-eb4b-420f-8956-8ac35d820043.png)

There are a number of bugzilla issues reported related to it [1](https://bugzilla.redhat.com/show_bug.cgi?id=2032498), [2](https://bugzilla.redhat.com/show_bug.cgi?id=2029709) and [3](https://www.mail-archive.com/package-announce@lists.fedoraproject.org/msg292869.html)

**Comment by daniruiz** [comment] 2022-03-04 21:18
Yes, I noticed it too. Unfortunately I think there's nothing I can do in the package to improve the speed :(

**Comment by daniruiz** [comment] 2022-05-26 11:07
I'm closing this as it isn't caused by the theme "per se" and other huge icon themes suffer from the same issue.

**Closed by daniruiz** 2022-05-26 11:07 UTC
